config/routes.rb
Rails.application.routes.draw do
  root to: 'documents#index'
  resources :documents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
    has_rich_text :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %w[ show edit update destroy ]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>
      <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="columns">
    <div class="column is-half">
      <div class="field">
        <div class="control">
          <%= form.text_field :title, class: "input is-large", placeholder: "Title" %>
        </div>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= form.rich_text_area :body %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: 'button is-link' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<section class="section">
  <div class="container">
    <%= render 'form', document: @document %>
    <br>
    <div class="buttons">
      <%= link_to 'Read', @document, class: 'button is-success' %>
      <%= link_to 'Back', documents_path, class: 'button' %>
    </div>
  </div>
</section>

app/views/documents/index.html.erb
<section class="section">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <div class="columns is-multiline is-vcentered">
      <div class="column is-3 has-text-centered">
        <%= link_to new_document_path do %>
          <span class="icon is-large">
            <i class="fas fa-plus has-text-link"></i>
          </span> <br>
          <span class="has-text-link has-text-weight-semibold">New Document</span>
        <% end %>
      </div>
      <% @documents.each do |document| %>
        <div class="column is-3 has-text-centered">
          <%= link_to document do %>
            <figure class="image is-128x128">
              <img src="https://bulma.io/images/placeholders/128x128.png">
            </figure>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/documents/new.html.erb
<section class="section">
  <div class="container">
    <%= render 'form', document: @document %> <br>
    <%= link_to 'Back', documents_path, class: "button" %>
  </div>
</section>

app/views/documents/show.html.erb
<section class="section">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <div class="hero">
      <div class="hero-body has-text-centered">
        <p class="title">
          <%= @document.title %>
        </p>
      </div>
    </div>
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <%= @document.body %>
          </div>
        </div>
      </article>
    </div>
    <%= link_to 'Edit', edit_document_path(@document), class: 'button is-info' %>
    <%= link_to 'Back', documents_path, class: 'button' %>
  </div>
</section>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <p class="has-text-weight-semibold has-text-grey">Online Word Processor</p>
      </a>
    </div>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Word Processor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>